name: Deploy to Cloudflare

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            API_TOKEN
            API_URL
            PAPERLESS_WHITELIST
        env:
          API_TOKEN: ${{ secrets.PAPERLESS_API_TOKEN }}
          API_URL: ${{ secrets.PAPERLESS_API_URL }}
          PAPERLESS_WHITELIST: ${{ secrets.PAPERLESS_WHITELIST }}
